/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteGrafico;

import com.panayotis.gnuplot.GNUPlotException;
import com.panayotis.gnuplot.JavaPlot;
import com.panayotis.gnuplot.plot.AbstractPlot;
import com.panayotis.gnuplot.style.PlotStyle;
import com.panayotis.gnuplot.style.Style;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.math.BigDecimal;
import java.util.LinkedList;
import java.util.List;
import javax.swing.BoundedRangeModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.text.DefaultCaret;
import Funcao.Funcao1;
import metodopassovariavel.IFuncao;
import metodopassovariavel.MetodoDePassoVariavel;
import metodopassovariavel.Ponto;
import metodopassovariavel.ResultSet;

/**
 *
 * @author Alessandro Campello Silva,<p>
 * Carlos Filipe M. Teixeira Jr.,<p>
 * Thadeu José Caldas Neves,<p>
 * Tomas M.G. de Siqueira.
 */
public class Pagina extends javax.swing.JFrame {

    private IFuncao funcao;
    private List<Ponto> pontos;
    private MetodoDePassoVariavel metodo;
    private Thread t;
    private static String path;

    public Pagina() {
        funcao = new Funcao1();
        
        initComponents();
        jLabel4.setText("Função: " + funcao.toString());
    }

    public void terminarExecucao() {
        jButton7.setEnabled(false);
    }
    
    public void setPontos(List<Ponto> pontos) {
        this.pontos = pontos;
    }

    public void mostrarErro(String mensagem, String titulo){
        JOptionPane.showMessageDialog(null, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
    }
    public void iniciarMetodo() {
        try {
            if (!t.isAlive()) {
                t = new Thread(metodo);
                t.start();
                jButton7.setEnabled(true);
            } else {
                mostrarErro("O método já está executando, espere até que ele\n"
                        + "termine para poder criar outra instância de execução.", "Método em execução");
            }
        } catch (NullPointerException e) {
            t = new Thread(metodo);
            t.start();
            jButton7.setEnabled(true);
        }
    }

    public void log(final String mensagem) {
        jTextArea1.append("\n" + mensagem);
    }

    private void executaMetodo(boolean exibiLog)
    {
        //Obtém os H's e inicia a lista de pontos
        Double valorHmax = Double.valueOf(jtfHMax.getText());
        BigDecimal hmax = BigDecimal.valueOf(valorHmax);
        Double valorHmin = Double.valueOf(jtfHMin.getText());
        BigDecimal hmin = BigDecimal.valueOf(valorHmin);
        Double valorH = Double.valueOf(jtfHInicial.getText());
        BigDecimal h = BigDecimal.valueOf(valorH);
        Double valorInicio = Double.valueOf(jtfHInicial.getText());
        BigDecimal inicio = BigDecimal.valueOf(valorInicio);
        Double valorFim = Double.valueOf(jtfFim.getText());
        BigDecimal fim = BigDecimal.valueOf(valorFim);
        
        pontos = new LinkedList<>();

        //Executa o método
        metodo = new MetodoDePassoVariavel(funcao, pontos,
                inicio,
                fim,
                BigDecimal.valueOf(0.5),
                new BigDecimal(1).divide(new BigDecimal(10).pow(5)),
                hmax, 
                hmin, 
                h, 
                this, 
                exibiLog);
        iniciarMetodo();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtfHMax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfHMin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfHInicial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfInicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfFim = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programação Científica - Método de Runge-Kutta-Fehlberg.");

        jtfHMax.setText("0.5");
        jtfHMax.setName("jtfHmax"); // NOI18N

        jLabel1.setText("H Max:");

        jtfHMin.setText("0.01");
        jtfHMin.setName("jtfHmin"); // NOI18N
        jtfHMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHMinActionPerformed(evt);
            }
        });

        jLabel2.setText("H Min:");

        jtfHInicial.setText("0.4");
        jtfHInicial.setName("jtfHInicial"); // NOI18N

        jLabel3.setText("HInicial");

        jButton1.setText("Rodar");
        jButton1.setName("BtnRodar"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRodarActionPerformed(evt);
            }
        });

        jButton2.setText("Rodar sem detalhes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRodarSemDetActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        makeTextAreaAutoScroll(jTextArea1);

        jButton3.setText("Gerar gráfico");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraGrafActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");
        jLabel4.setName("Formula"); // NOI18N

        jButton4.setText("Imprimir H");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpHActionPerformed(evt);
            }
        });

        jButton5.setText("Imprimir H, T e W");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpHTWActionPerformed(evt);
            }
        });

        jButton6.setText("Limpar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jButton7.setText("Parar execução");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        jButton8.setText("Alterar Path do GnuPlot");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltPathActionPerformed(evt);
            }
        });
        jButton8.setEnabled(false);

        jButton9.setText("Imprimir T");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpTActionPerformed(evt);
            }
        });

        jButton10.setText("Imprimir W");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpWActionPerformed(evt);
            }
        });

        jLabel5.setText("Inicio:");

        jtfInicio.setText("1");
        jtfInicio.setName("jtfInicio"); // NOI18N

        jLabel6.setText("Fim:");

        jtfFim.setText("10");
        jtfFim.setName("jtfFim"); // NOI18N

        jRadioButton1.setText("Função:  y' = y - x^2 + 1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Função: x^3+((x^4)*y)");

        jRadioButton3.setText("Função: Sin(x^2)");

        jRadioButton4.setText("Função: Gama*y");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfFim, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfHMax)
                            .addComponent(jtfHMin, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jtfHInicial))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfHMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jtfInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfHMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jtfFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfHInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRodarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRodarActionPerformed
        executaMetodo(true);        
    }//GEN-LAST:event_btnRodarActionPerformed

    private void btnRodarSemDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRodarSemDetActionPerformed
        executaMetodo(false);        
    }//GEN-LAST:event_btnRodarSemDetActionPerformed


    private void btnGeraGrafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraGrafActionPerformed
        if(System.getProperty("os.name").contains("Windows") && path == null){
            path = JOptionPane.showInputDialog(null, "Favor informar o caminho"
                    + " do executável wgnuplot.exe: ", "Caminho do executável", JOptionPane.PLAIN_MESSAGE);
        }
        if(path != null)
            if(!path.equals(""))
                jButton8.setEnabled(true);
        if((System.getProperty("os.name").contains("Windows") && jButton8.isEnabled()) ||
                (System.getProperty("os.name").equals("Linux"))){
            ResultSet result = new ResultSet(pontos);
            if(t != null){
                plot(result);
            } else {
                mostrarErro("Não existem pontos a serem plotados.\n"
                        + "Execute o método para obter os resultados.", "Resultados não detectados");
            }
        }
    }//GEN-LAST:event_btnGeraGrafActionPerformed

    private void btnImpHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpHActionPerformed
        try{
            if (!t.isAlive()) {
                for (Ponto ponto : pontos) {
                    log("H:" + ponto.getH());
                }
            } else {
                mostrarErro("O método ainda está executando, espere até que ele\n"
                        + "termine para poder mostrar os resultados.", "Método em execução");
            }
        } catch(NullPointerException e){
            mostrarErro("Não existem resultados a serem mostrados.\n"
                    + "Execute o método para obter mostrar os resultados.", "Resultados não detectados");
        }
    }//GEN-LAST:event_btnImpHActionPerformed

    private void btnImpHTWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpHTWActionPerformed
        try{
            if (!t.isAlive()) {
                for (Ponto ponto : pontos) {
                    log("T:" + ponto.getT() + " W:" + ponto.getW() + " H:" + ponto.getH());
                }
            } else {
                mostrarErro("O método ainda está executando, espere até que ele\n"
                        + "termine para poder mostrar os resultados.", "Método em execução");
            }
        } catch(NullPointerException e){
            mostrarErro("Não existem resultados a serem mostrados.\n"
                    + "Execute o método para poder mostrar os resultados.", "Resultados não detectados");
        }
    }//GEN-LAST:event_btnImpHTWActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        jTextArea1.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        metodo.setFLAG(false);
    }//GEN-LAST:event_btnPararActionPerformed

    private void btnAltPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltPathActionPerformed
        String temp = JOptionPane.showInputDialog(null, "Informe o novo caminho"
                + " do executável wgnuplot.exe: ", "Caminho do executável", JOptionPane.PLAIN_MESSAGE);
        if(temp != null)
            if(!temp.equals(""))
                path = temp;
    }//GEN-LAST:event_btnAltPathActionPerformed

    private void btnImpTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpTActionPerformed
        try{
            if (!t.isAlive()) {
                for (Ponto ponto : pontos) {
                    log("T:" + ponto.getT());
                }
            } else {
                mostrarErro("O método ainda está executando, espere até que ele\n"
                        + "termine para poder mostrar os resultados.", "Método em execução");
            }
        } catch(NullPointerException e){
            mostrarErro("Não existem resultados a serem mostrados.\n"
                    + "Execute o método para obter mostrar os resultados.", "Resultados não detectados");
        }
    }//GEN-LAST:event_btnImpTActionPerformed

    private void btnImpWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpWActionPerformed
        try{
            if (!t.isAlive()) {
                for (Ponto ponto : pontos) {
                    log("W:" + ponto.getW());
                }
            } else {
                mostrarErro("O método ainda está executando, espere até que ele\n"
                        + "termine para poder mostrar os resultados.", "Método em execução");
            }
        } catch(NullPointerException e){
            mostrarErro("Não existem resultados a serem mostrados.\n"
                    + "Execute o método para obter mostrar os resultados.", "Resultados não detectados");
        }
    }//GEN-LAST:event_btnImpWActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jtfHMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHMinActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public static void plot(ResultSet result){
        JavaPlot p = null;
        boolean caminhoErrado;
        if(System.getProperty("os.name").contains("Windows")){
            do{
                try{
                    p = new JavaPlot(path);
                    caminhoErrado = false;
                } catch (GNUPlotException e) {
                        path = JOptionPane.showInputDialog(null, "Executável não encontrado, informe o caminho correto para o executável: ",
                                "Executável não encontrado", JOptionPane.ERROR_MESSAGE);
                        if(path == null)
                            return;
                        caminhoErrado = true;
                }
            } while (caminhoErrado);
        } else {
            p = new JavaPlot();
        }
        p.addPlot(result);
        PlotStyle stl = ((AbstractPlot) p.getPlots().get(0)).getPlotStyle();
        stl.setStyle(Style.LINESPOINTS);
        stl.setPointSize(2);
        p.plot();
    }

    public static void makeTextAreaAutoScroll(JTextArea textArea) {

        // Get the text area's scroll pane :
        final JScrollPane scrollPane = (JScrollPane) (textArea.getParent().getParent());

        // Disable the auto scroll :
        ((DefaultCaret) textArea.getCaret()).setUpdatePolicy(DefaultCaret.NEVER_UPDATE);

        // Add a listener to the vertical scroll bar :
        scrollPane.getVerticalScrollBar().addAdjustmentListener(new AdjustmentListener() {

            private int _val = 0;
            private int _ext = 0;
            private int _max = 0;

            private final BoundedRangeModel _model = scrollPane.getVerticalScrollBar().getModel();

            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {

                // Get the new max :
                int newMax = _model.getMaximum();

                // If the new max has changed and if we were scrolled to bottom :
                if (newMax != _max && (_val + _ext == _max)) {

                    // Scroll to bottom :
                    _model.setValue(_model.getMaximum() - _model.getExtent());
                }

                // Save the new values :
                _val = _model.getValue();
                _ext = _model.getExtent();
                _max = _model.getMaximum();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtfFim;
    private javax.swing.JTextField jtfHInicial;
    private javax.swing.JTextField jtfHMax;
    private javax.swing.JTextField jtfHMin;
    private javax.swing.JTextField jtfInicio;
    // End of variables declaration//GEN-END:variables
}
